language:
    - python
python:
    - "2.7"
    - "3.5"
    - "3.6"

notifications:
  email: false

before_install:
    - "sudo apt-get install -qq python-scipy"

# command to install dependencies
install:
    - "pip install -r requirements.txt"
    - "pip install python-coveralls"
    - "pip install coveralls"
    - "pip install nose"
    - "pip install scikit-learn"

# command to run tests
script:
    - "nosetests --with-coverage --cover-erase --cover-package=DCASE2017-baseline-system -v -w tests/"

after_success:
    - "coveralls"
